# Generated by Django 3.2.9 on 2021-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
            ],
        ),
    ]
